export enum ErrorCode {
  NOT_REGISTERED = "ERR_NOT_REGISTERED",
  NICK_INVALID = "ERR_NICK_INVALID",
  NICK_ALREADY_TAKEN = "ERR_NICK_ALREADY_TAKEN",
  NOT_ON_CHANNEL = "ERR_NOT_CHANNEL",
  CHANNEL_INVALID = "ERR_CHANNEL_INVALID",
  CHANNEL_UNKNOWN = "ERR_CHANNEL_UNKNOWN",
}
